### ISSUE TITLE
HA 2023.7 problems.

### ISSUE THREAD

**Issue by MattWestb** [jacekk015/zha_quirks#12] opened 2023-07-06 08:08 UTC
Updating HA and is getting:
```
Logger: zhaquirks
Source: custom_zha_quirks/ts0601_trv_siterwell.py:60
First occurred: 09:39:02 (1 occurrences)
Last logged: 09:39:02

Unexpected exception importing custom quirk 'ts0601_trv_siterwell'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/zhaquirks/__init__.py", line 454, in setup
    importer.find_module(modname).load_module(modname)
  File "<frozen importlib._bootstrap_external>", line 605, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1120, in load_module
  File "<frozen importlib._bootstrap_external>", line 945, in load_module
  File "<frozen importlib._bootstrap>", line 290, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 721, in _load
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_zha_quirks/ts0601_trv_siterwell.py", line 60, in <module>
    class SiterwellManufCluster(TuyaManufClusterAttributes):
  File "/usr/local/lib/python3.11/site-packages/zigpy/zcl/__init__.py", line 165, in __init_subclass__
    raise TypeError(f"Duplicate definitions exist for {duplicates}")
TypeError: Duplicate definitions exist for ['window_alarm']
```
If need more logs i can providing it.

Thanks in advance Jacekk !!

**Comment by jacekk015** [comment] 2023-07-06 08:18
Hi,

unfortunately I'm on vacation in Italy. Please check for duplicate of window_alarm code. Did you maybe copy/paste something?

**Comment by MattWestb** [comment] 2023-07-06 08:20
Sounds great !!!
I using your standard quirk and have working well and i think its not copy past error but it can waiting than all TRV is idle for the moment and we can taking one look then you is back at home.

Have one great holiday in Bella Italia !!!!

**Comment by MattWestb** [comment] 2023-07-06 09:05
I was finding the typo in the quirks is was:
```
            SITERWELL_WINDOW_ALARM_ATTR: ("window_alarm", t.uint8_t, True),
            SITERWELL_VALVE_JAMMED_ALARM_ATTR: ("window_alarm", t.uint8_t, True),
```
and changing it to:
```
            SITERWELL_WINDOW_ALARM_ATTR: ("window_alarm", t.uint8_t, True),
            SITERWELL_VALVE_JAMMED_ALARM_ATTR: ("valve_alarm", t.uint8_t, True),
```
and ZHA is loading it OK and looks working but i have not testing the functions of window open and valve alarm.

Good for other user can getting the quirk working and you can taking one look later in October / November if its being OK then we need the TRVs working.


Great thanks for help and support for our TRVs !!!

**Comment by MattWestb** [comment] 2023-07-06 09:14
PR made so you can committing it if you like so its being easier for other users.

**Closed** 2023-07-06 09:43 UTC

**Comment by rofo69** [comment] 2023-07-12 06:52
Not sure that this is exactly the same quirk as mine, but I also noticed the above error on a siterwell quirk I was using (its also on a beca based TRV quirk that I have), but I also noticed that whilst the above one liner does allow the quirk to load, I was getting other errors. The errors, and the fix I applied are here:

https://community.home-assistant.io/t/zclattributedef-object-is-not-subscriptable/590645

**Comment by rofo69** [comment] 2023-07-12 08:42
Fundamentally it looks like update 2023.7 has changed the ZCLAttributeDef class, and any quirk that uses code like this:-

self.attributes[record.attrid][0]

Will break, and needs changing to this:

self.attributes[record.attrid].name

**Comment by jacekk015** [comment] 2023-07-15 19:56
@rofo69 That was actually corrected long time ago.
